### ISSUE TITLE
how to use ${revision} of flatten-maven-plugin together

### ISSUE THREAD

**Issue by Lingzhou314** [danielflower/multi-module-maven-release-plugin#132]
hello，
Can it be used with Flatten-Maven-Plugin? I want to use the $ {Revision} to manage multi-module version dependencies

i used 
`mvn clean install releaser:release`

I get these errors
```

[INFO] Going to revert changes because there was an error.
[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] ************************************
[ERROR] Could not execute the release plugin
[ERROR] ************************************
[ERROR] 
[ERROR] 
[ERROR] Cannot release with references to snapshot dependencies
[ERROR] The following dependency errors were found:
[ERROR]  * myproject references plugin dependency spring-boot-maven-plugin ${revision}
[ERROR]  * myproject-web-portal references plugin spring-boot-maven-plugin 2.0.1-SNAPSHOT


```

**Comment by kobynet** [comment]
This plugin replaces the maven module snapshot version with the real version, it knows how to handle version property as well (including ${revision} which is just a property after all (although it is known property for [friendl ci](https://maven.apache.org/maven-ci-friendly.html), etc...)).

Having said that, what flatten plugin does(among other things) is also replace the property with the real version, and therefore the two cannot co-exist together, they collide, so usually in CI flow where snapshots are used, you can use flatten plugin in order to have consumable snapshot artifacts, and when you want a release version, you can use this plugin which will also replace the artifact's version and you will also get a consumable artifact.

**Comment by Lingzhou314** [comment]
> 
thanks your comment, i got it
