### ISSUE TITLE
When mvn releaser:release is called with no modifications all module versions are incremented

### ISSUE THREAD

**Issue by chrisspelberg** [danielflower/multi-module-maven-release-plugin#4]

**Comment by danielflower** [comment]
Yes - that's by design actually as the thinking was there might be cases where you just want everything released, for whatever reason, and in general you'd only run a release build if there were changes to release.

What use case do you have? It could certainly be added as an optional config setting.

**Comment by chrisspelberg** [comment]
Thanks for your explanation!
I am evaluating this plugin for my current assignment, and I try to have everything as fool-proof as possible. I think a config setting would be nice, and I would suggest to set the default to not release when nothing has changed. What are your thoughts on this matter?

**Comment by danielflower** [comment]
If a setting is added, then it's better to default to the current behaviour so existing users aren't surprised. Something like:

    <actionWhenNoChangesDetected>ReleaseAll</actionWhenNoChangesDetected>

or

    <actionWhenNoChangesDetected>ReleaseNone</actionWhenNoChangesDetected>

Note that I won't have time to work on this in the foreseeable future but pull requests are welcome as always.

**Comment by kiiadi** [comment]
I've submitted a PR #47 to implement this behavior.

**Comment by danielflower** [comment]
Thanks! Released in version `2.1.2`
